spring:
  datasource:
    operations:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        pool-name: pool-zk
        maximum-pool-size: 50
        minimum-idle: 10
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
  configuration:
      #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
      map-underscore-to-camel-case: true
      cache-enabled: true
      default-statement-timeout: 30
      lazy-loading-enabled: true
      multiple-result-sets-enabled: true